---
#1.create droplet1
- hosts: localhost
  connection: local
  become: no
  roles:
    - { role: digitalocean, tags: [digitalocean] }
  vars:
    - droplet_name: mongo-test1

- hosts: localhost
  connection: local
  become: no
  gather_facts: false
  tasks:
    - name: Waiting for droplet DNS to propagate
      pause:
        seconds: 30
      when: droplet.changed
  vars: 
    - droplet_name: mongo-test1

- hosts: mongo-test1
  name: Test Connection and Determine Remote User
  gather_facts: false
  roles:
    - { role: connection, tags: [connection, always] }
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - local_python_interpreter: "{{ ansible_playbook_python }}"


#2.create droplet2
- hosts: localhost
  connection: local
  become: no
  roles:
    - { role: digitalocean, tags: [digitalocean] }
  vars:
    - droplet_name: mongo-test2

- hosts: localhost
  connection: local
  become: no
  gather_facts: false
  tasks:
    - name: Waiting for droplet DNS to propagate
      pause:
        seconds: 30
      when: droplet.changed
  vars: 
    - droplet_name: mongo-test2

- hosts: mongo-test2
  name: Test Connection and Determine Remote User
  gather_facts: false
  roles:
    - { role: connection, tags: [connection, always] }
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - local_python_interpreter: "{{ ansible_playbook_python }}"

#3.create droplet3
- hosts: localhost
  connection: local
  become: no
  roles:
    - { role: digitalocean, tags: [digitalocean] }
  vars:
    - droplet_name: mongo-test3

- hosts: localhost
  connection: local
  become: no
  gather_facts: false
  tasks:
    - name: Waiting for droplet DNS to propagate
      pause:
        seconds: 30
      when: droplet.changed
  vars: 
    - droplet_name: mongo-test3

- hosts: mongo-test3
  name: Test Connection and Determine Remote User
  gather_facts: false
  roles:
    - { role: connection, tags: [connection, always] }
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - local_python_interpreter: "{{ ansible_playbook_python }}"

#4. prepearing droplets
- hosts: do_droplet_in_memory
  gather_facts: no
  become: no
  roles:
    - { role: python-raw }

- hosts: do_droplet_in_memory
  become: no
  gather_facts: true
  tasks:
    - name: Get local machine's IP address
      set_fact:
        local_machine_ip: "{{ ansible_env['SSH_CLIENT'].split() | first }}"
      changed_when: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3

#5. configre droplets - swapfile,fail2ban,ufw,ntp,create user, upgrades,sshd
- hosts: do_droplet_in_memory
  become: no
  gather_facts: true
  roles:
    - { role: swapfile, tags: [swapfile] }
    - { role: fail2ban, tags: [fail2ban] }
    - { role: ufw, tags: [ufw] }
    - { role: ntp, tags: [ntp] }
    - { role: users, tags: [users] }
    - { role: unattended-upgrades, tags: [unattended-upgrades] }
    - { role: sshd, tags: [sshd] }
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - fail2ban_ip_whitelist: "{{ local_machine_ip }}/8"

#6. install and configure mongodb
- hosts: do_droplet_in_memory
  become: no
  gather_facts: true
  roles:
    - mongodb

